"""empty message

Revision ID: 52e6efa8870f
Revises: 
Create Date: 2022-05-24 20:19:24.280414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e6efa8870f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_companions',
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('companion_id', 'game_id')
    )
    op.create_unique_constraint(None, 'companions', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companions', type_='unique')
    op.drop_table('games_companions')
    # ### end Alembic commands ###
